import { AgentReplay, AgentRecorder } from '../../src/index.js';
import { wrapOpenAIForReplay } from '../../src/replay/openai.js';
import { OpenAI } from 'openai';

// 1. Create a simulated fixture artifact
const mockFixture = {
  version: '0.1',
  runId: 'demo-123',
  timestamp: new Date().toISOString(),
  agent: { name: 'demo' },
  events: [
    {
      id: 'evt-1',
      type: 'model_call',
      provider: 'openai',
      model: 'gpt-4o',
      messages: [{ role: 'user', content: 'What is the capital of France?' }]
    },
    {
      id: 'evt-2',
      type: 'model_response',
      response: 'The capital of France is Paris.',
      tokenUsage: { input: 15, output: 8, total: 23 }
    }
  ]
};

async function main() {
  console.log('--- Programmatic Streaming Replay Demo ---\n');
  
  // 2. Initialize replay with the mocked fixture
  const replay = new AgentReplay(mockFixture as any);
  
  // 3. Wrap a dummy OpenAI client
  const client = new OpenAI({ apiKey: 'dummy' });
  const wrappedClient = wrapOpenAIForReplay(client, replay);

  console.log('Executing streaming request...');
  
  // 4. Execute streaming request
  const stream = await wrappedClient.chat.completions.create({
    model: 'gpt-4o',
    messages: [{ role: 'user', content: 'What is the capital of France?' }],
    stream: true,
  });

  process.stdout.write('\nReplayed stream chunks: ');
  for await (const chunk of stream) {
    const content = chunk.choices[0]?.delta?.content;
    if (content) {
      process.stdout.write(content);
    }
  }
  
  console.log('\n\n--- Done ---');
  
  // 5. Observe the new artifact generated by Replay
  const recorder = replay.getRecorder();
  console.log('\nGenerated Artifact Events:');
  console.log(JSON.stringify(recorder.getArtifact().events, null, 2));
}

main();
